-- MySQL Script generated by MySQL Workbench
-- Mon Oct 14 08:32:02 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`restaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`restaurant` (
  `id` INT NOT NULL,
  `res_loc` VARCHAR(45) NULL,
  `res_employee_num` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employee` (
  `id` INT NOT NULL,
  `emp_fname` VARCHAR(45) NULL,
  `emp_lname` VARCHAR(45) NULL,
  `emp_dob` DATE NULL,
  `emp_address` VARCHAR(45) NULL,
  `emp_date_hired` DATE NULL,
  `restaurant_id` INT NOT NULL,
  PRIMARY KEY (`id`, `restaurant_id`),
  INDEX `fk_employee_restaurant_idx` (`restaurant_id` ASC) VISIBLE,
  CONSTRAINT `fk_employee_restaurant`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `mydb`.`restaurant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`supplier` (
  `id` INT NOT NULL,
  `supp_name` VARCHAR(45) NULL,
  `supp_contact` VARCHAR(45) NULL,
  `supp_add` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`onsite_customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`onsite_customer` (
  `id` INT NULL,
  `site_cust_dob` DATE NULL,
  `site_cust_fname` VARCHAR(45) NULL,
  `site_cust_lname` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`onsite_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`onsite_order` (
  `id` INT NOT NULL,
  `site_ord_num` VARCHAR(45) NULL,
  `site_ord_date` VARCHAR(45) NULL,
  `site_ord_amount` VARCHAR(45) NULL,
  `onsite_customer_id` INT NOT NULL,
  PRIMARY KEY (`id`, `onsite_customer_id`),
  INDEX `fk_onsite_order_onsite_customer1_idx` (`onsite_customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_onsite_order_onsite_customer1`
    FOREIGN KEY (`onsite_customer_id`)
    REFERENCES `mydb`.`onsite_customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`online_customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`online_customer` (
  `id` INT NOT NULL,
  `onl_cust_fname` VARCHAR(45) NULL,
  `onl_cust_fname` VARCHAR(45) NULL,
  `onl_cust_lname` VARCHAR(45) NULL,
  `onl_cust_dob` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`online_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`online_order` (
  `id` INT NOT NULL,
  `onl_ord_date` VARCHAR(45) NULL,
  `onl_ord_amount` VARCHAR(45) NULL,
  `online_customer_id` INT NOT NULL,
  PRIMARY KEY (`id`, `online_customer_id`),
  INDEX `fk_online_order_online_customer1_idx` (`online_customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_online_order_online_customer1`
    FOREIGN KEY (`online_customer_id`)
    REFERENCES `mydb`.`online_customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`chef`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`chef` (
  `id` INT NOT NULL,
  `id` VARCHAR(45) NOT NULL,
  `chef_position` VARCHAR(45) NULL,
  `chef_lname` VARCHAR(45) NULL,
  `chef_fname` VARCHAR(45) NULL,
  `onsite_order_id` INT NOT NULL,
  `onsite_order_onsite_customer_id` INT NOT NULL,
  `online_order_id` INT NOT NULL,
  `online_order_online_customer_id` INT NOT NULL,
  PRIMARY KEY (`id`, `id`, `onsite_order_id`, `onsite_order_onsite_customer_id`, `online_order_id`, `online_order_online_customer_id`),
  INDEX `fk_chef_onsite_order1_idx` (`onsite_order_id` ASC, `onsite_order_onsite_customer_id` ASC) VISIBLE,
  INDEX `fk_chef_online_order1_idx` (`online_order_id` ASC, `online_order_online_customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_chef_onsite_order1`
    FOREIGN KEY (`onsite_order_id` , `onsite_order_onsite_customer_id`)
    REFERENCES `mydb`.`onsite_order` (`id` , `onsite_customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chef_online_order1`
    FOREIGN KEY (`online_order_id` , `online_order_online_customer_id`)
    REFERENCES `mydb`.`online_order` (`id` , `online_customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product` (
  `id` INT NOT NULL,
  `prod_type` VARCHAR(45) NULL,
  `prod_date` DATE NULL,
  `prod_date_expire` DATE NULL,
  `prod_num_items` INT NULL,
  `supplier_id` INT NOT NULL,
  `chef_id` INT NOT NULL,
  `chef_id1` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `supplier_id`, `chef_id`, `chef_id1`),
  INDEX `fk_product_supplier1_idx` (`supplier_id` ASC) VISIBLE,
  INDEX `fk_product_chef1_idx` (`chef_id` ASC, `chef_id1` ASC) VISIBLE,
  CONSTRAINT `fk_product_supplier1`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `mydb`.`supplier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_chef1`
    FOREIGN KEY (`chef_id` , `chef_id1`)
    REFERENCES `mydb`.`chef` (`id` , `id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`delivery` (
  `id` INT NOT NULL,
  `delv_phone` VARCHAR(45) NULL,
  `delv_address` VARCHAR(45) NULL,
  `online_customer_id` INT NOT NULL,
  PRIMARY KEY (`id`, `online_customer_id`),
  INDEX `fk_delivery_online_customer1_idx` (`online_customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_delivery_online_customer1`
    FOREIGN KEY (`online_customer_id`)
    REFERENCES `mydb`.`online_customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`supplier_has_restaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`supplier_has_restaurant` (
  `supplier_id` INT NOT NULL,
  `restaurant_id` INT NOT NULL,
  PRIMARY KEY (`supplier_id`, `restaurant_id`),
  INDEX `fk_supplier_has_restaurant_restaurant1_idx` (`restaurant_id` ASC) VISIBLE,
  INDEX `fk_supplier_has_restaurant_supplier1_idx` (`supplier_id` ASC) VISIBLE,
  CONSTRAINT `fk_supplier_has_restaurant_supplier1`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `mydb`.`supplier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_supplier_has_restaurant_restaurant1`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `mydb`.`restaurant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
